/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fiap.soa;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author destro
 */
public class OrderClose extends javax.swing.JFrame {

    public OrderClose(int clientId, String cpf, String clientName, List<OrderProduct> orderProductList) {
        initComponents();
        this.clientId = clientId;
        this.cpf.setText(cpf);
        this.clientName.setText(clientName);
        this.orderProductList = orderProductList;

        // Calcula total do pedido
        orderTotal.setText(calculateTotal());

        // Exibir a lista de produtos
        orderList.setText(getTextProductList());

        backButton.setVisible(false);

    }

    private String calculateTotal() {
        // Calcular total
        double total = 0;
        for (OrderProduct o : orderProductList) {
            total += o.getFinalPrice();
        }

        return String.valueOf(total);
    }

    private String getTextProductList() {

        StringBuilder sb = new StringBuilder();

        sb.append("ID\tNOME\tPREÇO\tQTD\n");
        for (OrderProduct o : orderProductList) {
            sb.append(o.getId());
            sb.append("\t");
            sb.append(o.getName());
            sb.append("\t");
            sb.append(o.getFinalPrice());
            sb.append("\t");
            sb.append(o.getQuantity());
            sb.append("\n");
        }

        return sb.toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_data = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cpf_label = new javax.swing.JLabel();
        clientName = new javax.swing.JLabel();
        cpf = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        orderTotal = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Message = new javax.swing.JPanel();
        logMessage = new javax.swing.JTextField();
        PanelProductData = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        orderProductId = new javax.swing.JTextField();
        orderProductRemoveButton = new javax.swing.JButton();
        orderProductNewQuantity = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        orderProductUpdateQuantityButton = new javax.swing.JButton();
        orderProductAddButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderList = new javax.swing.JTextArea();
        orderCloseButton = new javax.swing.JButton();
        orderCancelButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_data.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Dados")));
        Panel_data.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                Panel_dataComponentHidden(evt);
            }
        });

        jLabel2.setText("Nome");

        cpf_label.setText("CPF");

        clientName.setText("CLIENT_NAME_VALUE");

        cpf.setText("CPF_VALUE");

        jLabel1.setText("Total");

        orderTotal.setText("ORDER_TOTAL");

        javax.swing.GroupLayout Panel_dataLayout = new javax.swing.GroupLayout(Panel_data);
        Panel_data.setLayout(Panel_dataLayout);
        Panel_dataLayout.setHorizontalGroup(
            Panel_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_dataLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(Panel_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_dataLayout.createSequentialGroup()
                        .addComponent(cpf_label)
                        .addGap(29, 29, 29)
                        .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Panel_dataLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(16, 16, 16)
                        .addGroup(Panel_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(orderTotal)
                            .addComponent(clientName, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 230, Short.MAX_VALUE))))
            .addGroup(Panel_dataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Panel_dataLayout.setVerticalGroup(
            Panel_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_dataLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(Panel_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cpf_label)
                    .addComponent(cpf))
                .addGap(6, 6, 6)
                .addGroup(Panel_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(clientName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(orderTotal))
                .addContainerGap())
        );

        getContentPane().add(Panel_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 650, 100));

        jLabel8.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel8.setText("Pedido");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Message.setBorder(javax.swing.BorderFactory.createTitledBorder("Avisos"));
        Message.setToolTipText("");

        logMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logMessageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MessageLayout = new javax.swing.GroupLayout(Message);
        Message.setLayout(MessageLayout);
        MessageLayout.setHorizontalGroup(
            MessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logMessage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
        );
        MessageLayout.setVerticalGroup(
            MessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        getContentPane().add(Message, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 649, 70));

        PanelProductData.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Produtos"));

        jLabel3.setText("ID");

        orderProductRemoveButton.setText("Remover Produto");
        orderProductRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderProductRemoveButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Nova quantidade");

        orderProductUpdateQuantityButton.setText("Atualizar quantidade");
        orderProductUpdateQuantityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderProductUpdateQuantityButtonActionPerformed(evt);
            }
        });

        orderProductAddButton.setText("Incluir Produto");
        orderProductAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderProductAddButtonActionPerformed(evt);
            }
        });

        orderList.setEditable(false);
        orderList.setColumns(20);
        orderList.setRows(5);
        jScrollPane1.setViewportView(orderList);

        javax.swing.GroupLayout PanelProductDataLayout = new javax.swing.GroupLayout(PanelProductData);
        PanelProductData.setLayout(PanelProductDataLayout);
        PanelProductDataLayout.setHorizontalGroup(
            PanelProductDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProductDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelProductDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelProductDataLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(PanelProductDataLayout.createSequentialGroup()
                        .addGroup(PanelProductDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelProductDataLayout.createSequentialGroup()
                                .addComponent(orderProductRemoveButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(orderProductAddButton))
                            .addGroup(PanelProductDataLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(10, 10, 10)
                                .addComponent(orderProductId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(6, 6, 6)
                                .addComponent(orderProductNewQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(orderProductUpdateQuantityButton)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        PanelProductDataLayout.setVerticalGroup(
            PanelProductDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProductDataLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelProductDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderProductId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(orderProductNewQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(orderProductUpdateQuantityButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelProductDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderProductRemoveButton)
                    .addComponent(orderProductAddButton))
                .addContainerGap())
        );

        getContentPane().add(PanelProductData, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 650, 270));

        orderCloseButton.setText("Finalizar Pedido");
        orderCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderCloseButtonActionPerformed(evt);
            }
        });
        getContentPane().add(orderCloseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, -1, -1));

        orderCancelButton.setText("Cancelar Pedido");
        orderCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderCancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(orderCancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, -1, -1));

        backButton.setLabel("Voltar Inicio");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, -1, -1));
        backButton.getAccessibleContext().setAccessibleName("Inicio");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Panel_dataComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_Panel_dataComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_dataComponentHidden

    private void logMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logMessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logMessageActionPerformed

    private void orderProductUpdateQuantityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderProductUpdateQuantityButtonActionPerformed

        logMessage.setText("Produto não esta na lsita");

        for (OrderProduct o : orderProductList) {
            if (o.getId() == Integer.valueOf(orderProductId.getText())) {

                try {
                    // Verifica estoque
                    JSONObject json = Order.getProduct(o.getId());

                    int quantity = json.optInt("quantity", 0);

                    // Verifica estoque
                    if (Integer.valueOf(orderProductNewQuantity.getText()) > quantity) {
                        logMessage.setText("Sem estoque");
                    } else {
                        o.setQuantity(Integer.valueOf(orderProductNewQuantity.getText()));

                        logMessage.setText("Quantidade do produto atualizado com sucesso");
                    }

                    break;
                } catch (Exception ex) {
                    Logger.getLogger(OrderClose.class.getName()).log(Level.SEVERE, null, ex);
                    logMessage.setText("[ER] " + ex.getMessage());
                }
            }
        }

        // Calcula total do pedido
        orderTotal.setText(calculateTotal());

        // Exibir a lista de produtos
        orderList.setText(getTextProductList());
    }//GEN-LAST:event_orderProductUpdateQuantityButtonActionPerformed

    private void orderProductAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderProductAddButtonActionPerformed
        Order order = new Order(clientId, cpf.getText(), clientName.getText(), orderProductList);
        order.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_orderProductAddButtonActionPerformed

    private void orderProductRemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderProductRemoveButtonActionPerformed
        logMessage.setText("Produto não esta na lsita");

        for (OrderProduct o : orderProductList) {
            if (o.getId() == Integer.valueOf(orderProductId.getText())) {
                orderProductList.remove(o);
                logMessage.setText("Produto removido com sucesso");
                break;
            }
        }

        // Calcula total do pedido
        orderTotal.setText(calculateTotal());

        // Exibir a lista de produtos
        orderList.setText(getTextProductList());
    }//GEN-LAST:event_orderProductRemoveButtonActionPerformed

    private void orderCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderCancelButtonActionPerformed

        // Limpa tabela
        orderProductList.clear();

        // Calcula total do pedido
        orderTotal.setText(calculateTotal());

        // Exibir a lista de produtos
        orderList.setText(getTextProductList());

        logMessage.setText("Pedido cancelado");

    }//GEN-LAST:event_orderCancelButtonActionPerformed

    private void orderCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderCloseButtonActionPerformed

        try {
            // Cria pedido com id do cliente e total da compra
            String message = "<store><action>create</action><order><client><id>" + clientId + "</id></client><total>" + calculateTotal() + "</total></order></store>";
            BrokerService bs = new BrokerService("order", message);

            JSONArray jsonList = new JSONArray(bs.getMessage());

            Integer orderId = null;

            if (jsonList.length() != 0) {
                orderId = jsonList.getJSONObject(0).getInt("GENERATED_KEY");
            }

            // Relaciona produtos com o pedido
            StringBuilder sb = new StringBuilder();
            sb.append("<store><action>addProducts</action>");
            sb.append("<order>");
            sb.append("<id>");
            sb.append(orderId);
            sb.append("</id>");
            sb.append("<products>");
            for (OrderProduct o : orderProductList) {
                sb.append("<product>");
                sb.append("<id>");
                sb.append(o.getId());
                sb.append("</id>");
                sb.append("<quantity>");
                sb.append(o.getQuantity());
                sb.append("</quantity>");
                sb.append("</product>");
            }
            sb.append("</products>");
            sb.append("</order>");
            sb.append("</store>");

            bs = new BrokerService("order", sb.toString());
            bs.getMessage();

            orderCloseButton.setVisible(false);
            orderCancelButton.setVisible(false);
            PanelProductData.setVisible(false);
            backButton.setVisible(true);

            logMessage.setText("Pedido concluído com sucesso");
        } catch (Exception e) {
            e.printStackTrace();
            logMessage.setText("[ER] " + e.getMessage());
        }


    }//GEN-LAST:event_orderCloseButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed

        Client client = new Client();
        client.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_backButtonActionPerformed

    private List<OrderProduct> orderProductList = new ArrayList<>();

    private int clientId;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Message;
    private javax.swing.JPanel PanelProductData;
    private javax.swing.JPanel Panel_data;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel clientName;
    private javax.swing.JLabel cpf;
    private javax.swing.JLabel cpf_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField logMessage;
    private javax.swing.JButton orderCancelButton;
    private javax.swing.JButton orderCloseButton;
    private javax.swing.JTextArea orderList;
    private javax.swing.JButton orderProductAddButton;
    private javax.swing.JTextField orderProductId;
    private javax.swing.JTextField orderProductNewQuantity;
    private javax.swing.JButton orderProductRemoveButton;
    private javax.swing.JButton orderProductUpdateQuantityButton;
    private javax.swing.JLabel orderTotal;
    // End of variables declaration//GEN-END:variables
}
