/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fiap.soa;

import java.util.ArrayList;
import java.util.List;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author destro
 */
public class Order extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Order(int clientId, String cpf, String clientName) {
        initComponents();
        this.cpf.setText(cpf);
        this.clientName.setText(clientName);

        PanelProductData.setVisible(false);
        orderCloseButton.setVisible(false);
    }

    public Order(int clientId, String cpf, String clientName, List<OrderProduct> orderProductList) {
        initComponents();
        this.cpf.setText(cpf);
        this.clientName.setText(clientName);
        this.orderProductList = orderProductList;

        PanelProductData.setVisible(false);
        orderCloseButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_data = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cpf_label = new javax.swing.JLabel();
        clientName = new javax.swing.JLabel();
        cpf = new javax.swing.JLabel();
        orderCloseButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Message = new javax.swing.JPanel();
        logMessage = new javax.swing.JTextField();
        PanelProductData = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        orderProductConfirmButton = new javax.swing.JButton();
        productName = new javax.swing.JLabel();
        productQuantity = new javax.swing.JLabel();
        productPrice = new javax.swing.JLabel();
        productMaxDiscount = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        productStatus = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        productId = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        orderProductQuantity = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_data.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Dados Cliente")));
        Panel_data.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                Panel_dataComponentHidden(evt);
            }
        });

        jLabel2.setText("Nome");

        cpf_label.setText("CPF");

        clientName.setText("CLIENT_NAME_VALUE");

        cpf.setText("CPF_VALUE");

        orderCloseButton.setText("Finalizar Pedido");
        orderCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderCloseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_dataLayout = new javax.swing.GroupLayout(Panel_data);
        Panel_data.setLayout(Panel_dataLayout);
        Panel_dataLayout.setHorizontalGroup(
            Panel_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_dataLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(Panel_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_dataLayout.createSequentialGroup()
                        .addComponent(cpf_label)
                        .addGap(29, 29, 29)
                        .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(Panel_dataLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(16, 16, 16)
                        .addComponent(clientName, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                        .addComponent(orderCloseButton))))
        );
        Panel_dataLayout.setVerticalGroup(
            Panel_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_dataLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(Panel_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cpf_label)
                    .addComponent(cpf))
                .addGap(6, 6, 6)
                .addGroup(Panel_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(Panel_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(clientName)
                        .addComponent(orderCloseButton))))
        );

        getContentPane().add(Panel_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 650, 80));

        jLabel8.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel8.setText("Pedido");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Message.setBorder(javax.swing.BorderFactory.createTitledBorder("Avisos"));
        Message.setToolTipText("");

        logMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logMessageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MessageLayout = new javax.swing.GroupLayout(Message);
        Message.setLayout(MessageLayout);
        MessageLayout.setHorizontalGroup(
            MessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logMessage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
        );
        MessageLayout.setVerticalGroup(
            MessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        getContentPane().add(Message, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 649, 70));

        PanelProductData.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Produto"));
        PanelProductData.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Nome");
        PanelProductData.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 29, -1, -1));

        jLabel5.setText("Estoque");
        PanelProductData.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 58, -1, -1));

        jLabel6.setText("Preço Unitário");
        PanelProductData.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 87, -1, -1));

        jLabel7.setText("Desconto %");
        PanelProductData.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 116, -1, -1));

        orderProductConfirmButton.setText("Confirmar");
        orderProductConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderProductConfirmButtonActionPerformed(evt);
            }
        });
        PanelProductData.add(orderProductConfirmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, -1, -1));

        productName.setText("PRODUCT_NAME");
        PanelProductData.add(productName, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 29, -1, -1));

        productQuantity.setText("PRODUCT_QUANTITY");
        PanelProductData.add(productQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 58, -1, -1));

        productPrice.setText("PRODUCT_PRICE");
        PanelProductData.add(productPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 87, -1, -1));

        productMaxDiscount.setText("PRODUC_MAX_DISCOUNT");
        PanelProductData.add(productMaxDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 116, -1, -1));

        jLabel9.setText("Status");
        PanelProductData.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 145, -1, -1));

        productStatus.setText("PRODUCT_STATUS");
        PanelProductData.add(productStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 145, 636, -1));

        getContentPane().add(PanelProductData, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 650, 225));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar Produto"));

        jLabel1.setText("Código do produto");

        jToggleButton1.setText("Pesquisar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Quantidade");

        orderProductQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderProductQuantityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productId, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(orderProductQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jToggleButton1)
                .addContainerGap(168, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(orderProductQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 650, -1));
        jPanel2.getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Panel_dataComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_Panel_dataComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_dataComponentHidden

    private void logMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logMessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logMessageActionPerformed

    private void orderProductQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderProductQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderProductQuantityActionPerformed

    public static JSONObject getProduct(int productId) throws Exception {
        JSONObject json = null;

        String message = "<store><action>select</action><product><id>" + productId + "</id></product></store>";

        BrokerService bs = new BrokerService("product", message);

        String response = null;

        response = bs.getMessage();

        JSONArray jsonList = new JSONArray(response);

        if (jsonList.length() != 0) {
            return jsonList.getJSONObject(0);
        }
        return json;
    }

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed

        try {
            JSONObject json = Order.getProduct(Integer.valueOf(productId.getText()));

            if (json == null) {
                PanelProductData.setVisible(false);

                logMessage.setText("Produto não encontrado");
            } else {
                PanelProductData.setVisible(true);
                orderProductConfirmButton.setVisible(true);

                logMessage.setText("Produto encontrado");
                productStatus.setText("OK");

                productName.setText(json.optString("name", ""));
                productQuantity.setText(json.optString("quantity", "0"));
                productPrice.setText(json.optString("price", "0.00"));
                productMaxDiscount.setText(json.optString("max_discount_percent", "0"));

                boolean outLineStore = json.optBoolean("out_line_store", false);
                boolean outLineFactory = json.optBoolean("out_line_factory", false);
                int quantity = json.optInt("quantity", 0);

                // Verifica estoque
                if (quantity < Integer.valueOf(orderProductQuantity.getText())) {
                    productStatus.setText("Sem estoque");
                    logMessage.setText("Sem estoque");
                    orderProductConfirmButton.setVisible(false);
                }

                // Fora de linha da empresa
                if (outLineStore) {
                    productStatus.setText("Fora de linha da empresa, prazo de máximo de 15 dias para troca");
                }

                // Fora de linha do fornecedor
                if (outLineFactory) {
                    productStatus.setText("Fora de linha do fornecedor, sem troca");
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
            logMessage.setText("[ER] " + e.getMessage());
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private List<OrderProduct> orderProductList = new ArrayList<OrderProduct>();

    private void orderProductConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderProductConfirmButtonActionPerformed

        OrderProduct orderProduct = new OrderProduct(Integer.valueOf(productId.getText()),
                productName.getText(), Integer.valueOf(orderProductQuantity.getText()), Integer.valueOf(productMaxDiscount.getText()), Double.valueOf(productPrice.getText()));

        orderProductList.add(orderProduct);

        int qtd = orderProductList.size();
        double total = 0;

        for (OrderProduct o : orderProductList) {
            total += o.getFinalPrice();
        }

        logMessage.setText("Produto adicionado ao carrinho com sucesso, qtd: " + qtd + ", total: " + total);

        PanelProductData.setVisible(false);

        // Habilita opção para fechar pedido
        orderCloseButton.setVisible(true);

    }//GEN-LAST:event_orderProductConfirmButtonActionPerformed

    private void orderCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderCloseButtonActionPerformed

        OrderClose orderClose = new OrderClose(clientId, cpf.getText(), clientName.getText(), orderProductList);

        orderClose.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_orderCloseButtonActionPerformed

    private int clientId;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Message;
    private javax.swing.JPanel PanelProductData;
    private javax.swing.JPanel Panel_data;
    private javax.swing.JLabel clientName;
    private javax.swing.JLabel cpf;
    private javax.swing.JLabel cpf_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField logMessage;
    private javax.swing.JButton orderCloseButton;
    private javax.swing.JButton orderProductConfirmButton;
    private javax.swing.JTextField orderProductQuantity;
    private javax.swing.JTextField productId;
    private javax.swing.JLabel productMaxDiscount;
    private javax.swing.JLabel productName;
    private javax.swing.JLabel productPrice;
    private javax.swing.JLabel productQuantity;
    private javax.swing.JLabel productStatus;
    // End of variables declaration//GEN-END:variables
}
